esphome:
  name: "traffic-light"
  friendly_name: "traffic-light"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "eCDTB2x5d3VFF8KOXJ8R1DyAJvPCbW8tFFDQs9jRjeg="

ota:
  - platform: esphome
    password: "bab432bb14def24732bef6015d4b1730"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Cam Fallback Hotspot"
    password: "w9woaYNOmnjk"

captive_portal:

# Web interface
web_server:
  port: 80

switch:
  - platform: gpio
    id: red_led
    name: "Red LED"
    pin: GPIO14
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: yellow_led
    name: "Yellow LED"
    pin: GPIO13
    restore_mode: ALWAYS_OFF

  - platform: gpio
    id: green_led
    name: "Green LED"
    pin: GPIO12
    restore_mode: ALWAYS_OFF

interval:
  - interval: 24s
    then:
      - switch.turn_on: red_led
      - switch.turn_off: yellow_led
      - switch.turn_off: green_led
      - delay: 10s

      - switch.turn_on: yellow_led
      - delay: 2s

      - switch.turn_off: red_led
      - switch.turn_off: yellow_led
      - switch.turn_on: green_led
      - delay: 10s

      - switch.turn_off: green_led
      - switch.turn_on: yellow_led
      - delay: 2s